name: terraform

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::854955106828:role/oidc-role
        aws-region: ${{ env.AWS_REGION }}

    - uses: opentofu/setup-opentofu@v1
    - run: tofu init

    - id: plan
      run: tofu plan -no-color
